### ISSUE TITLE
raw.php issue

### ISSUE THREAD

**Issue by yigit-alp** [seyahdoo/TabletopTurkeyifier#2]
it seems like pastebinp no longer supports raw.php?i=  :
pastebinp.com/raw.php?i=12345 will give an error in TS
changing this as
pastebinp.com/raw/ fixes this problem.

This can be done by changing the pastebin proxy in proxify.py as follows:

"http://pastebin.com/raw.php?i=": "http://pastebinp.com/raw/",
"http://pastebin.com/raw/": "http://pastebinp.com/raw/",

**Comment by seyahdoo** [comment]
thanks for reporting this issue. i will test and implement this fix soon.

**Comment by seyahdoo** [comment]
@yigit-alp can you link a workshop mod that has this issue, so that i can test and verify that it is working?

**Comment by seyahdoo** [comment]
i have been able to reproduce the issue with these two links
https://pastebinp.com/raw.php?i=VDJbPj6i
https://pastebinp.com/raw/VDJbPj6i

and will be merging your change soon

**Comment by seyahdoo** [comment]
I have merged your change, thanks for your contribution

Next time, to get a reaction faster than 2 months, you can try to contact me on my public discord server. Here is the link.
https://discord.gg/ZtDFmjXe7w
